### ISSUE TITLE
Security group name does not match those used in outputs

### ISSUE THREAD

**Issue by Nuxij** [devops-made-easy/terraform-aws-security-group#1]
The SG is named 'sg' but the outputs reference 'default':

* https://github.com/devops-made-easy/terraform-aws-security-group/blob/abcf865a84053c8566e56e1674c557d3bdd2377e/main.tf#L1
* https://github.com/devops-made-easy/terraform-aws-security-group/blob/abcf865a84053c8566e56e1674c557d3bdd2377e/outputs.tf#L2

A fix either way round if good with me 🙂 Current error:

```
Error: Reference to undeclared resource

  on .terraform\modules\network.sg\outputs.tf line 17, in output "egress_rules":
  17:   value = aws_security_group.default.egress

A managed resource "aws_security_group" "default" has not been declared in
module.network.module.sg.
```

**Comment by akloya** [comment]
Thanks for reporting the issue.  Fixed the issue in 0.0.3 version.
https://github.com/devops-made-easy/terraform-aws-security-group/commit/c2c7ad7d48405f5235da8115acc2b63763e10835
